-- File generated by the BNF Converter (bnfc 2.9.4).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelNumbers where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsNumbers

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transExp :: AbsNumbers.Exp -> Result
transExp x = case x of
  AbsNumbers.Plus exp1 exp2 -> failure x
  AbsNumbers.Minus exp1 exp2 -> failure x
  AbsNumbers.Times exp1 exp2 -> failure x
  AbsNumbers.Divide exp1 exp2 -> failure x
  AbsNumbers.Mod exp1 exp2 -> failure x
  AbsNumbers.Neg exp -> failure x
  AbsNumbers.Abs exp -> failure x
  AbsNumbers.Expo exp1 exp2 -> failure x
  AbsNumbers.Paren exp -> failure x
  AbsNumbers.Num integer -> failure x
